# Generated by Django 5.1.4 on 2025-01-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_image', models.ImageField(blank=True, null=True, upload_to='currency_images')),
                ('reconciliation', models.BooleanField(default=False)),
                ('transcation_id', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
