# Generated by Django 5.1.4 on 2025-01-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_author', models.CharField(default='user', max_length=255)),
                ('address', models.TextField(default='Nigeria')),
                ('event_description', models.TextField(default='owanbe')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_image', models.ImageField(blank=True, null=True, upload_to='currency_images')),
                ('reconciliation', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
