# Generated by Django 5.1.4 on 2025-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(default='event_1234', max_length=255, unique=True),
        ),
    ]
