# Generated by Django 5.1.4 on 2025-01-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_delete_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='events',
            name='postal_code',
            field=models.IntegerField(default=100001, max_length=6),
        ),
        migrations.AddField(
            model_name='events',
            name='state',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
