# Generated by Django 5.1.4 on 2025-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_author_alter_event_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(default='owanbe'),
        ),
    ]
