# Generated by Django 5.1.4 on 2025-01-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_address_events_street_address_events_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='LGA',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='postal_code',
            field=models.IntegerField(default=100001),
        ),
    ]
