# Generated by Django 5.1.4 on 2025-02-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_lga_alter_events_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='currency_image',
            field=models.TextField(null=True),
        ),
    ]
