# Generated by Django 5.1.4 on 2024-12-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
