# Generated by Django 5.1.4 on 2024-12-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='business_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_type',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
