# Generated by Django 5.1.4 on 2024-12-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_merchant_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='country',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='state',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='none'),
            preserve_default=False,
        ),
    ]
